components/Button.tsx
components/index.ts
pages/_app.tsx
pages/index.tsx
styles/global-styles.ts
styles/media.ts
styles/styled.d.ts
styles/theme.ts

- Design System 초기 구현
<br/>
> 작업한 목록
- Design System  구성
- Button Component 생성
<br />
기본적으로 사용할 `Design System`을 만들어 봤습니다. 🙏
**Styled Components** 기반으로는 처음 만들어봐서 피드백 해주시면 감사하겠습니다!! 👍

feat: 디자인 시스템 초기 구성

---

components/Box.tsx
components/Button.tsx
components/index.ts
pages/index.tsx
styles/theme.ts

- 신규 기능 추가
- 리펙토링
<br/>
> 작업한 목록
- Button component 스타일, props 타입 분리
- Box 컴포넌트 구현
<br />
Box 컴포넌트는 사용되는 곳이 좀 다양해서 필수 값들 위주로만 했습니다!   
사용되는 곳이 다양하다 보니 스타일을 미리 예측하기가 좀 그래서, 미디어 쿼리나 그 외 추가 스타일을 주고 싶으면 사용되는 부분에서 `Box`를 상속 받아서 추가 하는 식으로 하시는건 어떠신가욤?
혹시 더 좋은 의견 있으시면 코멘트 부탁드립니다!
ex)  Box에 media 쿼리를 사용할 경우
```javascript
const StyledBox = styled(Box)`
${media.desktop} {
width: 80px
}
`
```
ex) Box에 margin 값을 주고 싶은 경우
```javascript
const StyledBox = styled(Box)`
margin: 0 0 10px 0;
`
```

Feat: Box 컴포넌트 

---

components/Box.tsx
components/Header.tsx
components/index.ts
constants/breakpoints.ts
constants/headerMenus.ts
constants/path.ts
pages/index.tsx
styles/global-styles.ts
styles/media.ts
styles/styled.d.ts
styles/theme.ts

- 신규 기능 추가
- 리펙토링
<br/>
> 작업한 목록
- 헤더 컴포넌트 개발 (데스크탑)
- Path Enum 생성
- theme type 설정
<br />

feat: 헤더 컴포넌트 개발

---

components/Footer.tsx
components/index.ts
constants/yapp.ts
pages/index.tsx
styles/theme.ts

- 신규 기능 추가
<br/>
> 작업한 목록
- 푸터에 사용되는 텍스트 스타일 추가
- 푸터 구현
<br />
- 아직 디자인 안나온 부분이 많아서 그 부분은 임시로 만들고 @Todo 라고 주석 남겨놨습니다!

feat: Footer 컴포넌트 구현

---

.github/auto_assign.yml
.github/workflows/auto-assign-action.yml

- **신규 기능 추가**
- 버그 수정
- 리펙토링
- 문서 업데이트
<br/>
> 작업한 목록
pr 등록 시 자동으로 assignee, reviewers을 지정해주는 github action 추가해놨어요요 
이 pr이 머지된 이후에는 아래처럼 자동 등록 되어요
https://github.com/YAPP-admin/attendance-android/pull/23

feat: Implement Auto Assignee, Reviewers

---

styles/theme.ts

- 디자인 시스템 추가
<br/>
> 작업한 목록
- 현재 [figma](https://www.figma.com/file/G7pZL5C1f25TWhSgd3ov22/%5B20%EA%B8%B0-%EC%9A%B4%EC%98%81%5D-%EA%B3%B5%EC%8B%9D%EC%9B%B9-%EA%B0%9C%ED%8E%B8?node-id=262%3A447)에 나와있는 **색상**과 **letter-spacing**을 적용시켰습니다.

feat: 디자인 시스템 추가 (색상, letter-spacing)

---

constants/yapp.ts
pages-components/recruit/Enquiry/index.tsx
pages-components/recruit/RecruitBanner/index.tsx
pages-components/recruit/RecruitField/RecruitFieldExplain.tsx
utils/getRecruitLink.ts

- 신규 기능 추가
<br/>
> 작업한 목록
- 버튼 링크 연결
<br />

feat: 버튼 링크 연결

---

components/LayoutWrapper.tsx
pages-components/recruit/Enquiry/index.tsx

- 버그 수정
<br/>
> 작업한 목록
- 배경색, 버튼 색 수정
<br />

fix: background color change & button hover

---

components/Footer/index.tsx
components/LayoutWrapper.tsx
components/SEO.tsx
constants/yapp.ts
database/sitemap.ts
pages-components/recruit/FrequentlyAskedQuestions/index.tsx
pages-components/recruit/RecruitField/RecruitFieldExplain.tsx
pages-components/recruit/RecruitSchedule/index.tsx
pages/_document.tsx

- SEO 를 적용했습니다.
- 이제 Google Analytics 사용이 가능합니다.

feat: SEO & Google Analytics 적용

---

database/home.ts

fix: PM 요청 반영

---

components/GoogleAnalytics.tsx
pages/_document.tsx

fix: GA 수정

---

database/home.ts

- 버그 수정
<br/>
> 작업한 목록
- 활동회원, 런칭 서비스 수정
<br />

fix: 활동 회원, 런칭 서비스 수정

---

components/common/ProjectCard/index.tsx

- 버그 수정
<br/>
> 작업한 목록
- 서브카드 border-radius 효과 수정
<br />

fix: Project Detail Sub Card border-radius 수정

---

components/common/ProjectCard/index.tsx
components/project/ProjectContent/index.tsx
pages/project/[...slug].tsx

- 버그 수정
<br/>
> 작업한 목록
- description margin 오류 수정
- project sub card url 수정
- 더 둘러보기 나오는 카드 조건 수정
<br />
- 특이 사항 1
- 특이 사항 2

fix: project detail CSS & URL 수정

---

database/projects/20th/attendance.json

- 버그 수정
<br/>
> 작업한 목록
- 출석체크 어플 팀원 수정
<br />

fix: 출석체크 어플 팀원 수정

---

.storybook/main.js
components/common/BubbleMenu/index.tsx
components/common/ProjectCard/index.tsx
components/common/TabMenu/index.stories.tsx
components/common/TabMenu/index.tsx
components/common/index.ts
database/home.ts
database/project.ts
pages/index.tsx
pages/project/index.tsx
types/project.ts

- 프로젝트 페이지 추가 구현
- ALL 카테고리
- 버블 메뉴

feat: 프로젝트 페이지 추가 구현

---

pages/project/[...slug].tsx

- 버그 수정
<br/>
> 작업한 목록
- 모바일 모드일 때 이미지 깨짐 현상 수정
<br />

fix: 프로젝트 이미지 깨짐 현상 수정

---

hooks/useWindowDimensions.ts
pages/project/index.tsx

fix: 탭 메뉴 CSS 수정

---

components/home/IntroSection/index.tsx
package.json
yarn.lock

- 신규 기능 추가
<br/>
- 랜딩 페이지 next image 최적화했습니다.

feat: 이미지 최적화

---

components/common/AnimatedButton/index.stories.tsx
components/common/AnimatedButton/index.tsx
components/common/Button/index.tsx
components/common/index.ts
components/home/IntroSection/index.tsx
components/recruit/RecruitBanner/index.tsx
constants/yapp.ts
database/recruit.ts

- 리펙토링
<br/>
> 작업한 목록
- Home, Recruit 페이지에서 사용되는 애니메이션 버튼을 재사용 가능 컴포넌트로 분리
- 스토리북 작성
<br />

refactor: AnimatedButton 컴포넌트 리팩토링

---

package.json
yarn.lock

- eslint git hook 추가
<br/>
> 작업한 목록
- git hook & eslint 패키지 설치

feat: lint git hook 설정

---

components/recruit/RecruitField/RecruitFieldExplain.tsx
utils/getRecruitLink.ts

hotfix: props type 옵셔널 체이닝 처리

---

.github/auto_assign.yml
README.md

feat: 21기 운영진분들 잘 부탁드려요. 감사합니다. 🧡

---

database/home.ts

- #108 
<br/>
> 작업한 목록
- 후원사 목록 이미지 경로 수정
<br />
- 정적 리소스 데이터 수정할 경우 상수 잘 확인하기

#108 feat: 후원사 목록 이미지 경로 수정

---

components/recruit/RecruitField/RecruitFieldExplain.tsx
database/home.ts

close #120 
<br/>
> 작업한 목록
- 각 직군별 22기 모집 버튼 활성화
- 따끈한 최근 소식 불필요한 문구 제거

22기 모집 버튼 활성화

---

database/recruit.ts

close: #123 
> 작업한 목록
- 22기 지원기간 수정

fix: 22기 지원기간 수정

---

database/recruit.ts

close #125 
<br/>
> 작업한 목록
- 서류 접수 기간 요일 수정

Hotfix: 서류 접수 기간 요일 수정

---

components/recruit/RecruitField/RecruitFieldExplain.tsx
database/recruit.ts

close #136 
<br/>
> 작업한 목록
- 22기 지원 마감

Fix: 22기 지원마감

---

.github/auto_assign.yml

feat: 22기 운영진분들 잘 부탁드려요. 🧡

---

database/projects/21th/thismeme.json

close #139 
- thismeme 링크를 utm 심은 링크로 수정합니다.

fix(thismeme.json): thismeme 링크 수정

---

package.json
yarn.lock

- 버그 수정
<br/>
> 작업한 목록
- @React-Spring/web 패키지 버전 업데이트
깃헙액션 ci 과정에서 패키지 install 과정에 에러가 있어 해당 라이브러리 버전을 업데이트했습니다.
<br />

chore: @react-spring/web 버전 업데이트

---

components/home/IntroSection/Banner24th.tsx
components/home/IntroSection/index.tsx

- 버그 수정
+ 배너 반응형 개선
+ 완벽하게 배너 대응이 가능토록 리서치 필요

fix: 배너 관련 수정

---

database/home.ts
database/recruit.ts

- 문서 업데이트
<br/>
- 캐치 후원사 제거 (이미지는 보존)
- 채용 관련 하단 문구 수정

feat: 캐치 후원사 제거 및 채용 문의 하단 문구 수정

---

database/projects/22nd/coffice.json
database/projects/22nd/pyonsnalcolor.json

- 문서 업데이트
<br/>
- 22기 프로젝트 deployLink 누락된 것 제보받아서 추가

[fix]: 일부 프로젝트 배포 링크 누락된 것 추가

---

components/common/LayoutWrapper.tsx

- 버그 수정
<br/>
- home 탭 재이동시 스크롤 안되는 문제 수정 -> return문에서 current값 false로 수정

[25기 / HOTFIX]  home 탭으로 재이동시 스크롤

---

components/home/Dday/index.tsx

- 버그 수정
<br/>
- Dday 설정 시간을 UTC 한국시간대로 변경했습니다

fix : Dday 시간 수정

---

database/recruit.ts

- 신규 기능 추가
<br/>
- 26기 지원마감 -> 변수 수정
- 27기 사전알림 폼 링크 연결

[26기] 26기 지원마감

---

components/home/AnimatedTextSection/index.tsx

- 버그 수정
<br/>
> 작업한 목록
- AnimatedTextSectionContainer height 속성을 min-height 로 수정하여 애니메이션 버튼이 사라지는 현상을 수정하였습니다..

[26기] 애니메이션 영역 특정 높이에서 버튼이 사라지는 버그 수정
